services:
  nginx:
    container_name: myblog-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
      #- ./build/apache2/:/usr/local/apache2/conf/
    ports:
      - 80:80
    networks:
      - symfony
  php:
    container_name: myblog-php
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony_user:symfony_password@mysql:3306/symfony_db?serverVersion=5.7
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony

  mysql:
    container_name: myblog-mysql
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql/
    networks:
      - symfony
networks:
  symfony:
